version: '3.8'
services: 

    # Logging 
    seq:
        image: datalust/seq:latest
        ports:
            - 6341:80
        environment:
            ACCEPT_EULA: "Y"
    
    # Microsoft Sql Server
    sqldata:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "Pass@word"
            ACCEPT_EULA: "Y"   
        ports: 
            - "5433:1433"
        volumes:
            - ./docker-conf/mssql/yugiohinsight/sqldata:/var/opt/mssql
    
    # Message Broker
    rabbitmq:
        image: rabbitmq:management
        container_name: 'yugioh_insight_rabbitmq'
        hostname: yugioh_insight_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
            - ./docker-conf/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
            - ./docker-conf/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
        networks:
            - rabbitmq_net
        depends_on: 
            - rabbitmq_net
    
    # Yugioh Archetype article producer
    article-archetypes:
        container_name: article-archetypes
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.archetypes/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - Quartz__ArchetypeInformationJob=0 0 4 1/1 * ? *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=archetypearticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq

networks:
    rabbitmq_net:
        driver: bridge