version: '3.8'
services: 

    # Logging 
    seq:
        image: datalust/seq:latest
        ports:
            - 6341:80
        environment:
            ACCEPT_EULA: "Y"
    
    # Microsoft Sql Server
    sqldata:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "Pass@word"
            ACCEPT_EULA: "Y"   
        ports: 
            - "5433:1433"
    
    # Message Broker
    rabbitmq:
        image: rabbitmq:management
        container_name: 'yugioh_insight_rabbitmq'
        hostname: yugioh_insight_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
            - ./docker-conf/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
            - ./docker-conf/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
        networks:
            - rabbitmq_net
        depends_on: 
            - rabbitmq_net
    
    # Yugioh Archetypes
    article-archetypes:
        container_name: article-archetypes
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.archetypes/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=Archetypes
            - AppSettings__PageSize=500
            - Quartz__ArchetypeInformationJob=0 0 12 ? * TUE *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=archetypearticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq
    
    # Yugioh Archetypes Cards
    article-archetypes-cards:
        container_name: article-archetypes-cards
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.archetypes/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=Cards by archetype
            - AppSettings__PageSize=500
            - Quartz__ArchetypeInformationJob=0 0 1 ? * TUE *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=archetypecardsarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq

    # Yugioh Archetypes Support Cards
    article-archetypes-support-cards:
        container_name: article-archetypes-support-cards
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.archetypes/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=Cards by archetype support
            - AppSettings__PageSize=500
            - Quartz__ArchetypeInformationJob=0 0 2 ? * TUE *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=archetypesupportcardsarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq

    # Yugioh Tcg Cards
    article-tcg-cards:
        container_name: article-tcg-cards
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.cardinformation/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=TCG cards
            - AppSettings__PageSize=500
            - Quartz__CardInformationJob=0 58 23 ? * SUN *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=cardarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq
    
    # Yugioh Ocg Cards
    article-ocg-cards:
        container_name: article-ocg-cards
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.cardinformation/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=OCG cards
            - AppSettings__PageSize=500
            - Quartz__CardInformationJob=0 58 23 ? * SUN *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=cardarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq
    
    # Yugioh Card Tips
    article-card-tips:
        container_name: article-card-tips
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.cardinformation/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=Card Tips
            - AppSettings__PageSize=500
            - Quartz__CardInformationJob=0 0 12 ? 1/1 WED#3 *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=cardtipsarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq

    # Yugioh Card Rulings
    article-card-rulings:
        container_name: article-card-rulings
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.cardinformation/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=Card Rulings
            - AppSettings__PageSize=500
            - Quartz__CardInformationJob=0 0 12 ? 1/1 THU#3 *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=cardrulingsarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq

    # Yugioh Card Trivia
    article-card-trivia:
        container_name: article-card-trivia
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.cardinformation/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=Card Trivia
            - AppSettings__PageSize=500
            - Quartz__CardInformationJob=0 0 12 ? 1/1 FRI#3 *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=cardtriviaarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq

    # Yugioh Banlist
    article-banlist:
        container_name: article-banlist
        build: 
            context: ./src/wikia/article/src
            dockerfile: ./Presentation/article.latestbanlists/Dockerfile
        environment: 
            - AppSettings__WikiaDomainUrl=https://yugioh.fandom.com
            - AppSettings__Category=Forbidden & Limited Lists
            - AppSettings__PageSize=500
            - Quartz__BanlistInformationJob=0 0 4 1/1 * ? *
            - RabbitMqSettings__Host=localhost
            - RabbitMqSettings__Port=5672
            - RabbitMqSettings__Username=guest
            - RabbitMqSettings__Password=guest
            - RabbitMqSettings__ContentType=application/json
            - RabbitMqSettings__Exchanges__yugioh.headers.article__Headers__message-type=banlistarticle
            - RabbitMqSettings__Exchanges__yugioh.headers.article__PersistentMode=2
        depends_on: 
            - rabbitmq

networks:
    rabbitmq_net:
        driver: bridge