version: '3.8'
services: 
    rabbitmq:
        image: rabbitmq:management
        container_name: 'yugioh_insight_rabbitmq'
        hostname: yugioh_insight_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ~/docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/docker-conf/rabbitmq/log/:/var/log/rabbitmq
            - ~/docker-conf/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw
            - ~/docker-conf/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:rw
        networks:
            - rabbitmq_net
        depends_on: 
            - rabbitmq_net

networks:
    rabbitmq_net:
        driver: bridge